name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO_VERSION: '1.14'

jobs:

  misspell-check:
    runs-on: ubuntu-latest
    container: pouchcontainer/pouchlinter:v0.1.2
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Run markdownlint misspell
    #   run: find  ./* -name  "*"  | xargs misspell -error

    - name: Lint markdown files
      run: find  ./ -name  "*.md" | xargs mdl -r ~MD010,~MD013,~MD022,~MD024,~MD029,~MD031,~MD032,~MD033,~MD034,~MD036

  golang-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build the pixiu binariy
      run: go build -v ./...
    - name: Run pixiu unit test
      run: go test -v ./...
