name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO_VERSION: '1.17.3'

jobs:
  misspell-check:
    runs-on: ubuntu-latest
    container: pouchcontainer/pouchlinter:v0.1.2
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint markdown files
      run: find  ./ -name  "*.md" | grep -v '.github' | xargs mdl -r ~MD001,~MD004,~MD005,~MD006,~MD007,~MD010,~MD013,~MD022,~MD023,~MD024,~MD029,~MD031,~MD032,~MD033,~MD034,~MD036

  golang-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run go fmt test
      run: hack/verify-gofmt.sh
      env:
        GO111MODULE: auto

    - name: Build the localstorage binariy
      run: go build -v ./...

    - name: Run localstorage unit test
      run: go test -v ./...
